packages:
  - 'packages/*'
  - 'packages/starters/*'
  - 'packages/create/dist/*'
  - 'examples/*'
  - 'examples/import-bundling/*'
  - 'examples/integrations/*'
  - 'website'

catalog:
  '@types/node': ^25.5.0
  nitro: 3.0.260311-beta
  tsdown: ^0.21.7
  typescript: ^6.0.2
  vite: 8.0.3
  vitest: ^4.1.2
