import fs from 'node:fs'
import path from 'node:path'
import type { RouteManifestFile } from './route-manifest'

function quote(value: string): string {
	return JSON.stringify(value)
}

function paramsType(params: string[]): string {
	if (params.length === 0) return '{}'
	return `{ ${params.map(p => `${p}: string`).join('; ')} }`
}

export function renderRouteTypesDts(manifest: RouteManifestFile): string {
	const routeIds = manifest.routes.map(r => quote(r.id)).join(' | ') || 'never'
	const routePaths = manifest.routes.map(r => quote(r.path)).join(' | ') || 'never'
	const routePatterns = manifest.routes.map(r => quote(r.pattern)).join(' | ') || 'never'

	const paramsById = manifest.routes
		.map(r => `  ${quote(r.id)}: ${paramsType(r.params)}`)
		.join('\n')
	const paramsByPath = manifest.routes
		.map(r => `  ${quote(r.path)}: ${paramsType(r.params)}`)
		.join('\n')
	const paramsByPattern = manifest.routes
		.map(r => `  ${quote(r.pattern)}: ${paramsType(r.params)}`)
		.join('\n')

	return [
		'// Generated by Aero route contract generator. Do not edit manually.',
		'',
		`export type AeroRouteId = ${routeIds}`,
		`export type AeroRoutePath = ${routePaths}`,
		`export type AeroRoutePattern = ${routePatterns}`,
		'',
		'export interface AeroRouteParamsById {',
		paramsById,
		'}',
		'',
		'export interface AeroRouteParamsByPath {',
		paramsByPath,
		'}',
		'',
		'export interface AeroRouteParamsByPattern {',
		paramsByPattern,
		'}',
		'',
		'export interface AeroRouteSearchByPath {}',
		'',
	].join('\n')
}

export function renderRouteHelpersTs(manifest: RouteManifestFile): string {
	const paramByPattern = manifest.routes
		.map(r => `  ${quote(r.pattern)}: ${quote(r.path)}`)
		.join(',\n')

	return [
		'// Generated by Aero route contract generator. Do not edit manually.',
		"import type { AeroRoutePattern, AeroRouteParamsByPattern } from './route-types'",
		'',
		'const patternToPath: Record<string, string> = {',
		paramByPattern,
		'}',
		'',
		'export function pathFor<P extends AeroRoutePattern>(pattern: P, params: AeroRouteParamsByPattern[P]): string {',
		'  const pathPattern = patternToPath[pattern as string] ?? (pattern as string)',
		'  return pathPattern.replace(/:([A-Za-z0-9_]+)/g, (_: string, key: string) => {',
		'    const v = (params as Record<string, string>)[key]',
		'    if (v == null) throw new Error(`[aero] missing route param ${key} for pattern ${pattern as string}`)',
		'    return encodeURIComponent(String(v))',
		'  })',
		'}',
		'',
	].join('\n')
}

export function writeRouteTypesGenerated(root: string, manifest: RouteManifestFile): void {
	const outDir = path.join(root, '.aero', 'generated')
	fs.mkdirSync(outDir, { recursive: true })
	fs.writeFileSync(path.join(outDir, 'route-types.d.ts'), renderRouteTypesDts(manifest), 'utf8')
	fs.writeFileSync(path.join(outDir, 'route-helpers.ts'), renderRouteHelpersTs(manifest), 'utf8')
}
