import fs from 'node:fs'
import path from 'node:path'
import { pagePathToKey } from '../utils/routing'
import { getUnsupportedRoutePatternIssues, parseRoutePattern } from '../utils/route-pattern'

export interface RouteManifestEntry {
	id: string
	file: string
	pageName: string
	path: string
	pattern: string
	params: string[]
	isDynamic: boolean
	parentId: string | null
	isNotFound: boolean
}

export interface RouteManifestFile {
	version: 1
	generatedAt: string
	pagesDir: string
	routes: RouteManifestEntry[]
}

export interface RouteManifestDiagnostic {
	code: 'AERO_ROUTE'
	severity: 'error' | 'warning'
	message: string
	file?: string
}

export interface RouteManifestBuildResult {
	manifest: RouteManifestFile
	diagnostics: RouteManifestDiagnostic[]
}

function walkHtmlFiles(dir: string): string[] {
	if (!fs.existsSync(dir)) return []
	const out: string[] = []
	for (const item of fs.readdirSync(dir, { withFileTypes: true })) {
		const abs = path.join(dir, item.name)
		if (item.isDirectory()) {
			out.push(...walkHtmlFiles(abs))
			continue
		}
		if (item.isFile() && item.name.endsWith('.html')) out.push(abs)
	}
	return out
}

function toRoutePath(pageName: string): string {
	const normalized =
		pageName === 'index'
			? ''
			: pageName.endsWith('/index')
				? pageName.slice(0, -'/index'.length)
				: pageName
	if (!normalized) return '/'
	const segs = normalized.split('/').filter(Boolean)
	const mapped = segs.map(seg => {
		const match = /^\[([^\]]+)\]$/.exec(seg)
		return match ? `:${match[1]}` : seg
	})
	return '/' + mapped.join('/')
}

function toRouteId(pageName: string): string {
	const parts = parseRoutePattern(pageName).segments.map(seg => {
		if (seg.type === 'param') return `p:${encodeURIComponent(seg.name)}`
		return `s:${encodeURIComponent(seg.value)}`
	})
	return parts.join('/')
}

function toParentPath(routePath: string): string | null {
	if (routePath === '/' || routePath === '/404') return null
	const parts = routePath.split('/').filter(Boolean)
	if (parts.length === 0) return null
	parts.pop()
	return parts.length === 0 ? '/' : '/' + parts.join('/')
}

function parentRouteId(
	routes: Array<Pick<RouteManifestEntry, 'id' | 'path' | 'pageName'>>,
	routePath: string
): string | null {
	const parentPath = toParentPath(routePath)
	if (!parentPath) return null
	const candidates = routes.filter(r => r.path === parentPath)
	if (candidates.length === 0) return null
	const preferred = candidates.find(c => c.pageName.endsWith('/index') || c.pageName === 'index')
	return (preferred ?? candidates[0]).id
}

export function buildRouteManifestWithDiagnostics(
	root: string,
	clientDir: string
): RouteManifestBuildResult {
	const pagesDirRel = path.join(clientDir, 'pages').split(path.sep).join('/')
	const pagesDirAbs = path.resolve(root, clientDir, 'pages')
	const pageFiles = walkHtmlFiles(pagesDirAbs).sort((a, b) => a.localeCompare(b))
	const diagnostics: RouteManifestDiagnostic[] = []

	const draft = pageFiles.map(fileAbs => {
		const relRoot = path.relative(root, fileAbs).split(path.sep).join('/')
		const pageName = pagePathToKey(relRoot)
		const routePath = toRoutePath(pageName)
		const pattern = pageName
		const unsupported = getUnsupportedRoutePatternIssues(pattern)
		for (const issue of unsupported) {
			const hint =
				issue.reason === 'catch-all'
					? 'Catch-all syntax is not supported yet. Use static segments or single-parameter [name] segments.'
					: issue.reason === 'optional'
						? 'Optional parameter syntax is not supported yet. Use explicit static routes or separate files.'
						: 'Use bracket parameter segments like [id] with alphanumeric/underscore names.'
			diagnostics.push({
				code: 'AERO_ROUTE',
				severity: 'error',
				message: `Unsupported route segment ${JSON.stringify(issue.segment)} in ${JSON.stringify(pattern)}. ${hint}`,
				file: relRoot,
			})
		}
		const segs = parseRoutePattern(pattern).segments
		const params = segs.flatMap(s => (s.type === 'param' ? [s.name] : []))
		return {
			id: toRouteId(pageName),
			file: relRoot,
			pageName,
			path: pageName === '404' ? '/404' : routePath,
			pattern,
			params,
			isDynamic: params.length > 0,
			isNotFound: pageName === '404',
		}
	})

	const routes: RouteManifestEntry[] = draft.map(r => ({
		...r,
		parentId: parentRouteId(draft, r.path),
	}))

	const byPath = new Map<string, RouteManifestEntry[]>()
	for (const route of routes) {
		const current = byPath.get(route.path) ?? []
		current.push(route)
		byPath.set(route.path, current)
	}
	for (const [routePath, entries] of byPath.entries()) {
		if (entries.length <= 1) continue
		diagnostics.push({
			code: 'AERO_ROUTE',
			severity: 'error',
			message:
				`Duplicate route path ${JSON.stringify(routePath)} generated by multiple page files: ` +
				entries.map(e => e.file).join(', '),
			file: entries[0]?.file,
		})
	}

	return {
		manifest: {
			version: 1,
			generatedAt: new Date().toISOString(),
			pagesDir: pagesDirRel,
			routes,
		},
		diagnostics,
	}
}

export function buildRouteManifest(root: string, clientDir: string): RouteManifestFile {
	return buildRouteManifestWithDiagnostics(root, clientDir).manifest
}

function routeManifestEqualsIgnoringGeneratedAt(
	a: RouteManifestFile,
	b: RouteManifestFile
): boolean {
	if (a.version !== b.version) return false
	if (a.pagesDir !== b.pagesDir) return false
	return JSON.stringify(a.routes) === JSON.stringify(b.routes)
}

export function writeRouteManifestGenerated(
	root: string,
	clientDir: string
): { manifestPath: string; manifest: RouteManifestFile; diagnostics: RouteManifestDiagnostic[] } {
	const { manifest, diagnostics } = buildRouteManifestWithDiagnostics(root, clientDir)
	const outDir = path.join(root, '.aero', 'generated')
	fs.mkdirSync(outDir, { recursive: true })
	const manifestPath = path.join(outDir, 'route-manifest.json')

	if (fs.existsSync(manifestPath)) {
		try {
			const existingRaw = fs.readFileSync(manifestPath, 'utf8')
			const existing = JSON.parse(existingRaw) as RouteManifestFile
			if (routeManifestEqualsIgnoringGeneratedAt(existing, manifest)) {
				manifest.generatedAt = existing.generatedAt
			}
		} catch {
			// If existing manifest is unreadable, overwrite with fresh generated output.
		}
	}

	const nextText = JSON.stringify(manifest, null, 2) + '\n'
	const prevText = fs.existsSync(manifestPath) ? fs.readFileSync(manifestPath, 'utf8') : null
	if (prevText !== nextText) {
		fs.writeFileSync(manifestPath, nextText, 'utf8')
	}
	return { manifestPath, manifest, diagnostics }
}
