/**
 * Generates `.aero/cache/types/snippets.d.ts` — ambient module declarations for
 * `@content/snippets/*` imports derived from `@snippet` markers in source files.
 */
import fs from 'node:fs'
import path from 'node:path'
import { isSnippetModulePath, parseSnippetModule, SNIPPETS_SOURCE_REL } from './snippets'

export const DEFAULT_SNIPPETS_DTS_REL = path.join('.aero', 'cache', 'types', 'snippets.d.ts')

export { SNIPPETS_SOURCE_REL }

export type SnippetModuleEntry = {
	readonly moduleSpecifier: string
	readonly exportNames: readonly string[]
}

const EMPTY_SNIPPETS_DTS =
	`/** Auto-generated by Aero — do not edit. No snippet modules found under content/snippets/. */\n`

function writeIfChanged(filePath: string, content: string): void {
	const prev = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : null
	if (prev !== content) fs.writeFileSync(filePath, content, 'utf8')
}

function moduleSpecifierForSnippetFile(root: string, fullPath: string): string {
	const rel = path.relative(path.join(root, 'content'), fullPath).replace(/\\/g, '/')
	return `@content/${rel}`
}

function collectSnippetModuleEntry(root: string, fullPath: string): SnippetModuleEntry | null {
	if (!isSnippetModulePath(fullPath)) return null
	const source = fs.readFileSync(fullPath, 'utf-8')
	const snippets = parseSnippetModule(source, fullPath)
	const exportNames = [...snippets.keys()].sort()
	if (exportNames.length === 0) return null
	return {
		moduleSpecifier: moduleSpecifierForSnippetFile(root, fullPath),
		exportNames,
	}
}

/**
 * Scan `content/snippets/` for snippet module files and collect export names per module.
 */
export function collectSnippetModuleEntries(root: string): SnippetModuleEntry[] {
	const snippetsDir = path.join(root, SNIPPETS_SOURCE_REL)
	if (!fs.existsSync(snippetsDir)) return []

	const out: SnippetModuleEntry[] = []
	for (const name of fs.readdirSync(snippetsDir, { withFileTypes: true })) {
		if (!name.isFile()) continue
		const fullPath = path.join(snippetsDir, name.name)
		if (!isSnippetModulePath(fullPath)) continue
		try {
			const entry = collectSnippetModuleEntry(root, fullPath)
			if (entry) out.push(entry)
		} catch {
			continue
		}
	}
	return out.sort((a, b) => a.moduleSpecifier.localeCompare(b.moduleSpecifier))
}

/** Render `snippets.d.ts` with one `declare module` per snippet source file. */
export function renderSnippetsDts(entries: readonly SnippetModuleEntry[]): string {
	if (entries.length === 0) return EMPTY_SNIPPETS_DTS

	const blocks: string[] = []
	blocks.push(`/**`)
	blocks.push(` * Auto-generated by Aero — do not edit. Regenerated in dev/build and \`aero check --types\`.`)
	blocks.push(` */`)
	blocks.push(``)

	for (const entry of entries) {
		const escaped = entry.moduleSpecifier.replace(/'/g, "\\'")
		blocks.push(`declare module '${escaped}' {`)
		for (const name of entry.exportNames) {
			blocks.push(`\texport const ${name}: Snippet`)
		}
		blocks.push(`}`)
		blocks.push(``)
	}

	return blocks.join('\n')
}

/**
 * Write snippet module types next to the project root (creates directories).
 *
 * @returns `{ path, moduleCount }`.
 */
export function writeSnippetTypesGenerated(
	root: string,
	outPath = path.join(root, DEFAULT_SNIPPETS_DTS_REL)
): { path: string; moduleCount: number } {
	const snippetsDir = path.join(root, SNIPPETS_SOURCE_REL)
	const entries = fs.existsSync(snippetsDir) ? collectSnippetModuleEntries(root) : []
	const text = renderSnippetsDts(entries)
	fs.mkdirSync(path.dirname(outPath), { recursive: true })
	writeIfChanged(outPath, text)
	return { path: outPath, moduleCount: entries.length }
}
