/**
 * Generates `.aero/cache/types/components.d.ts` — augments `Aero.ComponentRegistry` with
 * `'tag-name': { props: TypeName }` using namespaces to avoid type name collisions.
 */

import fs from 'node:fs'
import path from 'node:path'
import { getPropsTypeFromBuildScript } from './build-script-analysis'
import { collectBuildScriptTypeDeclarationTexts } from './build-scope-bindings'
import { parse } from './parser'

export const DEFAULT_COMPONENT_REGISTRY_REL = path.join(
	'.aero',
	'cache',
	'types',
	'components.d.ts'
)

export type ComponentRegistryEntry = {
	readonly relPath: string
	readonly tag: string
	readonly namespaceId: string
	readonly propsTypeName: string | null
	readonly typeDeclarationText: string
}

function kebabBasename(filePath: string): string {
	const base = path.basename(filePath, path.extname(filePath))
	return base.replace(/\\/g, '/').split('/').pop() ?? base
}

function toNsId(tag: string): string {
	return `__tag_${tag.replace(/[^a-zA-Z0-9]+/g, '_')}`
}

/**
 * Scan `componentsDir` for `*.html` and build registry metadata from each file's build script.
 */
export function collectComponentRegistryEntries(componentsDir: string): ComponentRegistryEntry[] {
	if (!fs.existsSync(componentsDir)) return []
	const out: ComponentRegistryEntry[] = []

	function walk(dir: string): void {
		for (const name of fs.readdirSync(dir, { withFileTypes: true })) {
			const full = path.join(dir, name.name)
			if (name.isDirectory()) {
				walk(full)
				continue
			}
			if (!name.isFile() || !name.name.endsWith('.html')) continue

			const source = fs.readFileSync(full, 'utf-8')
			const parsed = parse(source)
			const script = parsed.buildScript?.content ?? ''
			const tag = kebabBasename(full)
			const props = getPropsTypeFromBuildScript(script)
			const typeTexts = collectBuildScriptTypeDeclarationTexts(script.trim() ? [script] : [])
			const relPath = full
			out.push({
				relPath,
				tag,
				namespaceId: toNsId(tag),
				propsTypeName: props?.typeName ?? null,
				typeDeclarationText: typeTexts.join('\n\n'),
			})
		}
	}

	walk(componentsDir)
	return out.sort((a, b) => a.tag.localeCompare(b.tag))
}

/**
 * Render `components.d.ts` source. Omits registry keys when `propsTypeName` is missing.
 */
export function renderComponentRegistryDts(entries: readonly ComponentRegistryEntry[]): string {
	const blocks: string[] = []
	blocks.push(`/**`)
	blocks.push(
		` * Auto-generated by Aero — do not edit. Regenerate via the CLI check command or build.`
	)
	blocks.push(` */`)
	blocks.push(``)
	blocks.push(`declare namespace AeroRegistryGenerated {`)

	for (const e of entries) {
		if (!e.typeDeclarationText.trim()) continue
		blocks.push(`\texport namespace ${e.namespaceId} {`)
		for (const line of e.typeDeclarationText.split('\n')) {
			blocks.push(`\t\t${line}`)
		}
		blocks.push(`\t}`)
		blocks.push(``)
	}

	blocks.push(`}`)
	blocks.push(``)
	blocks.push(`declare namespace Aero {`)
	blocks.push(`\tinterface ComponentRegistry {`)

	for (const e of entries) {
		if (!e.propsTypeName) continue
		blocks.push(
			`\t\t'${e.tag}': { props: AeroRegistryGenerated.${e.namespaceId}.${e.propsTypeName} }`
		)
	}

	blocks.push(`\t}`)
	blocks.push(`}`)
	blocks.push(``)

	return blocks.join('\n')
}

/**
 * Write registry next to the project root (creates directories).
 *
 * @returns `{ path, entryCount }` or null when nothing to write.
 */
export function writeComponentRegistryDts(
	root: string,
	componentsDir: string,
	outPath = path.join(root, DEFAULT_COMPONENT_REGISTRY_REL)
): { path: string; entryCount: number } {
	const entries = collectComponentRegistryEntries(componentsDir)
	const text =
		entries.length === 0
			? `/** Auto-generated stub — no components found. */\ndeclare namespace Aero {\n\tinterface ComponentRegistry {}\n}\n`
			: renderComponentRegistryDts(entries)
	const withProps = entries.filter(e => e.propsTypeName)
	fs.mkdirSync(path.dirname(outPath), { recursive: true })
	fs.writeFileSync(outPath, text, 'utf-8')
	return { path: outPath, entryCount: withProps.length }
}
