/**
 * `aero check` — validate aero config, content collections, and template compilation without starting a server.
 */
import type { AeroConfig, AeroConfigFunction } from '@aero-js/config'
import { loadAeroConfig } from '@aero-js/config'
import {
	contentSchemaIssuesToAeroDiagnostics,
	loadAllCollections,
	loadContentConfigFileSync,
} from '@aero-js/content'
import { initProcessor } from '@aero-js/content/processor'
import {
	checkTemplateTypesWithFile,
	compileTemplate,
	loadProjectTsConfig,
	writeComponentRegistryDts,
} from '@aero-js/core/compile-check'
import type { AeroDiagnostic } from '@aero-js/core/diagnostics'
import {
	exitCodeForDiagnostics,
	formatDiagnosticsTerminal,
	unknownToAeroDiagnostics,
} from '@aero-js/core/diagnostics'
import {
	buildRouteManifestWithDiagnostics,
	writeRouteManifestGenerated,
} from '@aero-js/core/routing/route-manifest'
import { writeRouteTypesGenerated } from '@aero-js/core/routing/route-typegen'
import {
	loadTsconfigAliases,
	mergeWithDefaultAliases,
	resolveDirs,
} from '@aero-js/core/utils/aliases'
import { Effect } from 'effect'
import fs from 'node:fs'
import path from 'node:path'

function toPageNameFromPagesDir(absFile: string, pagesDir: string): string {
	const rel = path
		.relative(pagesDir, absFile)
		.split(path.sep)
		.join('/')
		.replace(/\.html$/i, '')
	if (rel === 'index') return 'index'
	if (rel.endsWith('/index')) return rel
	return rel
}

function toRoutePathFromPageName(pageName: string): string {
	const normalized =
		pageName === 'index'
			? ''
			: pageName.endsWith('/index')
				? pageName.slice(0, -'/index'.length)
				: pageName
	if (!normalized) return '/'
	const mapped = normalized
		.split('/')
		.filter(Boolean)
		.map(seg => {
			const match = /^\[([^\]]+)\]$/.exec(seg)
			return match ? `:${match[1]}` : seg
		})
	return '/' + mapped.join('/')
}

function collectRouteContractDiagnosticsFallback(
	root: string,
	clientDir: string
): AeroDiagnostic[] {
	const pagesDir = path.join(root, clientDir, 'pages')
	const files = walkHtmlFiles(pagesDir)
	const byRoute = new Map<string, string[]>()
	const diagnostics: AeroDiagnostic[] = []

	for (const abs of files) {
		const pageName = toPageNameFromPagesDir(abs, pagesDir)
		const pageSegments = pageName.split('/').filter(Boolean)
		for (const seg of pageSegments) {
			if (!seg.startsWith('[') || !seg.endsWith(']')) continue
			const inner = seg.slice(1, -1)
			const validParam = /^[A-Za-z_][A-Za-z0-9_]*$/.test(inner)
			if (validParam) continue
			const hint = inner.startsWith('...')
				? 'Catch-all syntax is not supported yet. Use static segments or single-parameter [name] segments.'
				: inner.endsWith('?')
					? 'Optional parameter syntax is not supported yet. Use explicit static routes or separate files.'
					: 'Use bracket parameter segments like [id] with alphanumeric/underscore names.'
			diagnostics.push({
				severity: 'error',
				code: 'AERO_ROUTE',
				message: `Unsupported route segment ${JSON.stringify(seg)} in ${JSON.stringify(pageName)}. ${hint}`,
				file: abs,
			})
		}

		if (pageName === '404') continue
		const routePath = toRoutePathFromPageName(pageName)
		const current = byRoute.get(routePath) ?? []
		current.push(abs)
		byRoute.set(routePath, current)
	}

	for (const [routePath, entries] of byRoute.entries()) {
		if (entries.length <= 1) continue
		diagnostics.push({
			severity: 'error',
			code: 'AERO_ROUTE',
			message:
				`Duplicate route path ${JSON.stringify(routePath)} generated by multiple page files: ` +
				entries.map(e => path.relative(root, e).split(path.sep).join('/')).join(', '),
			file: entries[0],
		})
	}

	return diagnostics
}

function collectRouteCollisionDiagnostics(root: string, clientDir: string): AeroDiagnostic[] {
	const dedupe = (items: AeroDiagnostic[]): AeroDiagnostic[] => {
		const seen = new Set<string>()
		const out: AeroDiagnostic[] = []
		for (const item of items) {
			const key = `${item.code}|${item.file ?? ''}|${item.message}`
			if (seen.has(key)) continue
			seen.add(key)
			out.push(item)
		}
		return out
	}

	const fallback = collectRouteContractDiagnosticsFallback(root, clientDir)
	try {
		const { diagnostics } = buildRouteManifestWithDiagnostics(root, clientDir)
		const fromManifest = diagnostics.map(d => ({
			severity: d.severity,
			code: d.code,
			message: d.message,
			...(d.file ? { file: path.resolve(root, d.file) } : {}),
		}))
		return dedupe([...fromManifest, ...fallback])
	} catch (err) {
		if (fallback.length > 0) return dedupe(fallback)
		return unknownToAeroDiagnostics(err)
	}
}

function routeArtifactIoDiagnostic(root: string, message: string): AeroDiagnostic {
	return {
		severity: 'error',
		code: 'AERO_ROUTE',
		message,
		file: path.join(root, '.aero', 'generated'),
	}
}

function ensureRouteArtifacts(root: string, clientDir: string): AeroDiagnostic[] {
	try {
		const { manifest } = writeRouteManifestGenerated(root, clientDir)
		writeRouteTypesGenerated(root, manifest)
		return []
	} catch (err) {
		const detail = err instanceof Error ? err.message : String(err)
		return [
			routeArtifactIoDiagnostic(
				root,
				`[aero check] Failed to write generated route artifacts under .aero/generated: ${detail}`
			),
		]
	}
}

function isDebugEnabled(): boolean {
	const v = process.env.AERO_LOG
	return v === 'debug' || (typeof v === 'string' && v.split(/[\s,]+/).includes('debug'))
}

function startDebugSpan(name: string): { end(details?: string): void } {
	const t0 = Date.now()
	if (isDebugEnabled()) process.stderr.write(`[aero] span:start ${name}\n`)
	return {
		end(details?: string): void {
			if (!isDebugEnabled()) return
			const dt = Date.now() - t0
			process.stderr.write(`[aero] span:end ${name} (${dt}ms${details ? `, ${details}` : ''})\n`)
		},
	}
}

function recordCliDiagnosticsMetrics(diagnostics: readonly AeroDiagnostic[]): void {
	if (!isDebugEnabled() || diagnostics.length === 0) return
	process.stderr.write(
		`[aero] metrics[cli-check] +${diagnostics.length} diagnostics ` +
			`codes=${diagnostics.map(d => d.code).join(',')}\n`
	)
}

function resolveAeroConfigObject(loaded: AeroConfig | AeroConfigFunction | null): AeroConfig {
	if (!loaded) return {}
	if (typeof loaded === 'function') {
		return loaded({ command: 'build', mode: 'production' })
	}
	return loaded
}

function contentConfigPathFromAero(root: string, aero: AeroConfig): string {
	const c = aero.content
	if (c === true || c === undefined || c === false) {
		return 'content.config.ts'
	}
	return c.config ?? 'content.config.ts'
}

function shouldRunContentCheck(aero: AeroConfig, root: string, relPath: string): boolean {
	if (aero.content === true) return true
	if (typeof aero.content === 'object' && aero.content) return true
	const abs = path.resolve(root, relPath)
	return fs.existsSync(abs)
}

function walkHtmlFiles(dir: string): string[] {
	if (!fs.existsSync(dir)) return []
	const files: string[] = []
	for (const item of fs.readdirSync(dir, { withFileTypes: true })) {
		const fullPath = path.join(dir, item.name)
		if (item.isDirectory()) {
			files.push(...walkHtmlFiles(fullPath))
			continue
		}
		if (item.isFile() && item.name.endsWith('.html')) {
			files.push(fullPath)
		}
	}
	return files
}

function templateDirs(root: string, clientRel: string): string[] {
	const base = path.join(root, clientRel)
	return [path.join(base, 'pages'), path.join(base, 'components'), path.join(base, 'layouts')]
}

export type AeroCheckOptions = {
	/**
	 * Run TypeScript checks on merged `<script is:build>` and `{ }` interpolations (same virtual files as Volar),
	 * using the workspace tsconfig (paths, strict). Writes `.aero/cache/types/components.d.ts` for the component registry.
	 */
	types?: boolean
}

/**
 * Run validation checks for an Aero project directory.
 *
 * @returns Exit code `0` when clean; otherwise {@link exitCodeForDiagnostics} (10–14) from the primary error, matching static build buckets.
 */
export async function runAeroCheck(root: string, options: AeroCheckOptions = {}): Promise<number> {
	return Effect.runPromise(
		Effect.gen(function* () {
			const span = startDebugSpan('cli-check')
			const diagnostics: AeroDiagnostic[] = []
			const loadedRaw = yield* Effect.try({
				try: () => loadAeroConfig(root),
				catch: err => err,
			}).pipe(
				Effect.catchAll(err => {
					diagnostics.push(...unknownToAeroDiagnostics(err))
					return Effect.succeed<ReturnType<typeof loadAeroConfig>>(null)
				})
			)
			const aero = resolveAeroConfigObject(loadedRaw)

			const dirs = resolveDirs(aero.dirs)
			const mergedAliases = mergeWithDefaultAliases(loadTsconfigAliases(root), root, dirs)
			const resolvePath = mergedAliases.resolve
			diagnostics.push(...collectRouteCollisionDiagnostics(root, dirs.client))
			diagnostics.push(...ensureRouteArtifacts(root, dirs.client))

			const contentRel = contentConfigPathFromAero(root, aero)
			if (shouldRunContentCheck(aero, root, contentRel)) {
				const contentLoad = loadContentConfigFileSync(root, contentRel)
				if (!contentLoad.ok) {
					if (contentLoad.reason === 'missing' && aero.content === true) {
						diagnostics.push({
							severity: 'error',
							code: 'AERO_CONFIG',
							message: `[aero check] content is enabled but no config file at "${path.resolve(root, contentRel)}".`,
							file: path.resolve(root, contentRel),
						})
					} else if (contentLoad.reason === 'error') {
						diagnostics.push(...unknownToAeroDiagnostics(contentLoad.error))
					}
				} else {
					yield* Effect.tryPromise({
						try: async () => {
							await initProcessor(contentLoad.config.markdown)
							const { schemaIssues } = await loadAllCollections(contentLoad.config, root, {
								contentConfigPath: contentRel,
							})
							if (schemaIssues.length > 0) {
								diagnostics.push(...contentSchemaIssuesToAeroDiagnostics(schemaIssues, 'error'))
							}
						},
						catch: err => err,
					}).pipe(
						Effect.catchAll(err => {
							diagnostics.push(...unknownToAeroDiagnostics(err))
							return Effect.void
						})
					)
				}
			}

			const htmlFiles: string[] = []
			for (const dir of templateDirs(root, dirs.client)) {
				htmlFiles.push(...walkHtmlFiles(dir))
			}
			const sorted = [...new Set(htmlFiles)].sort()
			const runTypes = options.types === true
			const projectTs = runTypes ? loadProjectTsConfig(root) : null
			const componentsDir = path.join(root, dirs.client, 'components')
			const registryWritten = runTypes ? writeComponentRegistryDts(root, componentsDir) : null
			const registryPath = registryWritten?.path

			yield* Effect.forEach(
				sorted,
				file =>
					Effect.try({
						try: () => fs.readFileSync(file, 'utf-8'),
						catch: err => err,
					}).pipe(
						Effect.catchAll(err => {
							diagnostics.push(...unknownToAeroDiagnostics(err))
							return Effect.succeed<string | null>(null)
						}),
						Effect.flatMap(source => {
							if (source === null) return Effect.void
							return Effect.try({
								try: () => {
									compileTemplate(source, {
										root,
										resolvePath,
										importer: file,
										onWarning: warning => {
											diagnostics.push({
												severity: 'warning',
												code: warning.code,
												message: warning.message,
												file: warning.file ?? file,
												...(warning.line !== undefined && warning.column !== undefined
													? {
															span: {
																file: warning.file ?? file,
																line: warning.line,
																column: warning.column,
															},
														}
													: {}),
											})
										},
									})
									if (runTypes) {
										for (const issue of checkTemplateTypesWithFile(source, file, {
											root,
											project: projectTs ?? undefined,
											interpolations: true,
											componentRegistryDtsPath: registryPath,
										})) {
											const code =
												issue.kind === 'interpolation' ? 'AERO_COMPILE' : 'AERO_BUILD_SCRIPT'
											diagnostics.push({
												severity: 'error',
												code,
												message: issue.message,
												file: issue.file,
												span: {
													file: issue.file,
													line: issue.line,
													column: issue.column,
													lineEnd: issue.lineEnd,
													columnEnd: issue.columnEnd,
												},
											})
										}
									}
								},
								catch: err => err,
							}).pipe(
								Effect.catchAll(err => {
									diagnostics.push(...unknownToAeroDiagnostics(err))
									return Effect.void
								}),
								Effect.asVoid
							)
						})
					),
				{ discard: true }
			)

			const errors = diagnostics.filter(d => d.severity === 'error')
			const warnings = diagnostics.filter(d => d.severity === 'warning')
			if (warnings.length > 0) {
				const warningText = formatDiagnosticsTerminal(warnings, { plain: true })
				process.stderr.write(warningText + (warningText.endsWith('\n') ? '' : '\n'))
			}
			if (errors.length === 0) {
				span.end(warnings.length > 0 ? `warnings=${warnings.length}` : 'clean')
				return 0
			}
			recordCliDiagnosticsMetrics(errors)
			const text = formatDiagnosticsTerminal(errors, { plain: true })
			process.stderr.write(text + (text.endsWith('\n') ? '' : '\n'))
			span.end(`errors=${errors.length}`)
			return exitCodeForDiagnostics(errors)
		})
	)
}
