/**
 * Pure emitters for generated `.aero/nitro.config.mjs` content.
 */

import path from 'node:path'
import { serializeInline } from './nitro-config-normalize'

export interface EmitGeneratedNitroConfigInput {
	root: string
	serverScanDir: string
	aeroPlugins: string[]
	effectiveAeroRouteRules: Record<string, unknown>
	replace: Record<string, string>
	/** Relative import path from `.aero/` to user nitro config, or null when none. */
	importPath: string | null
	/** True when user config loaded successfully as an object. */
	userConfigOk: boolean
	normalizedUserScanDirs: string[]
	normalizedUserTasks: unknown
	normalizedUserModules: unknown
	normalizedUserErrorHandler: unknown
	normalizedUserImports: unknown
	normalizedUserAlias: unknown
	normalizedUserServerAssets: unknown
	normalizedUserPublicAssets: unknown
	normalizedUserServerEntry: unknown
}

/** Emit generated nitro.config.mjs source for the three merge branches. */
export function emitGeneratedNitroConfigContent(input: EmitGeneratedNitroConfigInput): string {
	const {
		root,
		serverScanDir,
		aeroPlugins,
		effectiveAeroRouteRules,
		replace,
		importPath,
		userConfigOk,
		normalizedUserScanDirs,
		normalizedUserTasks,
		normalizedUserModules,
		normalizedUserErrorHandler,
		normalizedUserImports,
		normalizedUserAlias,
		normalizedUserServerAssets,
		normalizedUserPublicAssets,
		normalizedUserServerEntry,
	} = input

	const outputDir = path.join(root, '.output')

	if (importPath === null) {
		return `// Generated by Aero — do not edit
import { defineNitroConfig } from 'nitro/config'

export default defineNitroConfig(${JSON.stringify(
			{
				rootDir: '..',
				output: { dir: outputDir },
				scanDirs: [serverScanDir],
				plugins: aeroPlugins,
				routeRules: effectiveAeroRouteRules,
				noPublicDir: true,
				replace,
			},
			null,
			2
		)})
`
	}

	if (userConfigOk) {
		return `// Generated by Aero — do not edit
import { defineNitroConfig } from 'nitro/config'
import userNitroConfig from ${JSON.stringify(importPath)}

const userNitroConfigObject =
	userNitroConfig && typeof userNitroConfig === 'object' && !Array.isArray(userNitroConfig)
		? userNitroConfig
		: {}

const aeroScanDirs = ${JSON.stringify([serverScanDir], null, 2)}
const userScanDirs = ${serializeInline(normalizedUserScanDirs)}

const aeroPlugins = ${serializeInline(aeroPlugins)}

const userTasks = ${serializeInline(normalizedUserTasks)}

const userModules = ${serializeInline(normalizedUserModules)}

const userErrorHandler = ${serializeInline(normalizedUserErrorHandler)}

const userImports = ${serializeInline(normalizedUserImports)}

const userAlias = ${serializeInline(normalizedUserAlias)}

const userServerAssets = ${serializeInline(normalizedUserServerAssets)}

const userPublicAssets = ${serializeInline(normalizedUserPublicAssets)}

const userServerEntry = ${serializeInline(normalizedUserServerEntry)}

const aeroRouteRules = ${JSON.stringify(effectiveAeroRouteRules, null, 2)}
const userRouteRules =
	userNitroConfigObject.routeRules &&
	typeof userNitroConfigObject.routeRules === 'object' &&
	!Array.isArray(userNitroConfigObject.routeRules)
		? userNitroConfigObject.routeRules
		: {}

const userReplace =
	userNitroConfigObject.replace &&
	typeof userNitroConfigObject.replace === 'object' &&
	!Array.isArray(userNitroConfigObject.replace)
		? userNitroConfigObject.replace
		: {}

export default defineNitroConfig({
	...userNitroConfigObject,
	rootDir: '..',
	output: ${JSON.stringify({ dir: outputDir }, null, 2)},
	scanDirs: Array.from(new Set([...userScanDirs, ...aeroScanDirs])),
	plugins: aeroPlugins,
	...(userTasks !== undefined ? { tasks: userTasks } : {}),
	...(userModules !== undefined ? { modules: userModules } : {}),
	...(userErrorHandler !== undefined ? { errorHandler: userErrorHandler } : {}),
	...(userImports !== undefined ? { imports: userImports } : {}),
	...(userAlias !== undefined ? { alias: userAlias } : {}),
	...(userServerAssets !== undefined ? { serverAssets: userServerAssets } : {}),
	...(userPublicAssets !== undefined ? { publicAssets: userPublicAssets } : {}),
	...(userServerEntry !== undefined ? { serverEntry: userServerEntry } : {}),
	routeRules: {
		...aeroRouteRules,
		...userRouteRules,
	},
	noPublicDir: true,
	replace: {
		...userReplace,
		...${JSON.stringify(replace, null, 2)},
	},
})
`
	}

	return `// Generated by Aero — do not edit
import { defineNitroConfig } from 'nitro/config'
import userNitroConfig from ${JSON.stringify(importPath)}

const aeroScanDirs = ${JSON.stringify([serverScanDir], null, 2)}
const userScanDirs =
	Array.isArray(userNitroConfig?.scanDirs) ? userNitroConfig.scanDirs : []

const aeroRouteRules = ${JSON.stringify(effectiveAeroRouteRules, null, 2)}
const userRouteRules =
	userNitroConfig &&
	typeof userNitroConfig === 'object' &&
	!Array.isArray(userNitroConfig) &&
	userNitroConfig.routeRules &&
	typeof userNitroConfig.routeRules === 'object' &&
	!Array.isArray(userNitroConfig.routeRules)
		? userNitroConfig.routeRules
		: {}

export default defineNitroConfig({
	extends: ${JSON.stringify(importPath)},
	rootDir: '..',
	output: ${JSON.stringify({ dir: outputDir }, null, 2)},
	scanDirs: Array.from(new Set([...userScanDirs, ...aeroScanDirs])),
	plugins: ${JSON.stringify(aeroPlugins, null, 2)},
	routeRules: Object.fromEntries(
		Object.entries(aeroRouteRules).filter(([route]) => !(route in userRouteRules))
	),
	noPublicDir: true,
	replace: ${JSON.stringify(replace, null, 2)},
})
`
}
