import type { RedirectRule } from '../types'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'
import { redirectsToRouteRules } from '../utils/redirects'

const require = createRequire(import.meta.url)

export const NITRO_CONFIG_NAMES = [
	'nitro.config.ts',
	'nitro.config.mts',
	'nitro.config.cts',
	'nitro.config.js',
	'nitro.config.mjs',
	'nitro.config.cjs',
] as const

type NitroConfigObject = Record<string, unknown>

export type LoadProjectNitroConfigDetailedResult =
	| { ok: true; filePath: string; config: NitroConfigObject }
	| { ok: false; reason: 'not-found' }
	| { ok: false; reason: 'invalid-export'; filePath: string }
	| { ok: false; reason: 'load-error'; filePath: string; error: unknown }

export interface GeneratedNitroConfigResult {
	aeroDir: string
	filePath: string
	content: string
	conflictingRedirects: string[]
	userConfigFile: string | null
}

interface GeneratedNitroConfigOptions {
	root: string
	serverDir: string
	redirects?: RedirectRule[]
	distDir: string
	apiPrefix: string
	warn?: (message: string) => void
}

export function findProjectNitroConfigFile(root: string): string | null {
	for (const name of NITRO_CONFIG_NAMES) {
		const filePath = path.join(root, name)
		if (existsSync(filePath)) return filePath
	}
	return null
}

export function loadProjectNitroConfigDetailed(root: string): LoadProjectNitroConfigDetailedResult {
	const filePath = findProjectNitroConfigFile(root)
	if (!filePath) return { ok: false, reason: 'not-found' }

	try {
		const jiti = require('jiti')(root, { esmResolve: true })
		const mod = jiti('./' + path.basename(filePath))
		const config = mod?.default ?? mod
		if (config && typeof config === 'object' && !Array.isArray(config)) {
			return { ok: true, filePath, config: config as NitroConfigObject }
		}
		return { ok: false, reason: 'invalid-export', filePath }
	} catch (error) {
		return { ok: false, reason: 'load-error', filePath, error }
	}
}

export function writeGeneratedNitroConfig({
	root,
	serverDir,
	redirects,
	distDir,
	apiPrefix,
	warn,
}: GeneratedNitroConfigOptions): GeneratedNitroConfigResult {
	const aeroDir = path.join(root, '.aero')
	mkdirSync(aeroDir, { recursive: true })

	const userConfig = loadProjectNitroConfigDetailed(root)
	const userConfigFile = userConfig.ok ? userConfig.filePath : findProjectNitroConfigFile(root)
	const userRouteRules =
		userConfig.ok &&
		userConfig.config.routeRules &&
		typeof userConfig.config.routeRules === 'object' &&
		!Array.isArray(userConfig.config.routeRules)
			? (userConfig.config.routeRules as Record<string, unknown>)
			: {}

	if (!userConfig.ok && userConfig.reason === 'load-error') {
		warn?.(
			`[aero] Failed to inspect ${path.basename(userConfig.filePath)} for redirect conflicts. Nitro will still extend it during build.`
		)
	}
	if (!userConfig.ok && userConfig.reason === 'invalid-export') {
		warn?.(
			`[aero] ${path.basename(userConfig.filePath)} does not export an object. Redirect conflict detection was skipped.`
		)
	}

	const aeroRouteRules = redirectsToRouteRules(redirects ?? [])
	const conflictingRedirects = Object.keys(aeroRouteRules).filter(route => route in userRouteRules)
	const effectiveAeroRouteRules = Object.fromEntries(
		Object.entries(aeroRouteRules).filter(([route]) => !conflictingRedirects.includes(route))
	)

	if (conflictingRedirects.length > 0) {
		warn?.(
			`[aero] Skipping redirect-generated Nitro routeRules that already exist in ${path.basename(userConfigFile ?? 'nitro.config')}: ${conflictingRedirects.join(', ')}`
		)
	}

	const replace = {
		'process.env.AERO_DIST': JSON.stringify(distDir),
		'process.env.AERO_API_PREFIX': JSON.stringify(apiPrefix),
	}

	const serverScanDir = path.join(root, serverDir)
	const importPath =
		userConfigFile === null
			? null
			: toRelativeModulePath(aeroDir, userConfigFile).replace(/\\/g, '/')

	const content =
		importPath === null
			? `// Generated by Aero — do not edit
import { defineNitroConfig } from 'nitro/config'

export default defineNitroConfig(${JSON.stringify(
				{
					rootDir: '..',
					output: { dir: path.join(root, '.output') },
					scanDirs: [serverScanDir],
					routeRules: effectiveAeroRouteRules,
					noPublicDir: true,
					replace,
				},
				null,
				2
			)})
`
			: `// Generated by Aero — do not edit
import { defineNitroConfig } from 'nitro/config'
import userNitroConfig from ${JSON.stringify(importPath)}

const aeroScanDirs = ${JSON.stringify([serverScanDir], null, 2)}
const userScanDirs =
	Array.isArray(userNitroConfig?.scanDirs) ? userNitroConfig.scanDirs : []

const aeroRouteRules = ${JSON.stringify(effectiveAeroRouteRules, null, 2)}
const userRouteRules =
	userNitroConfig &&
	typeof userNitroConfig === 'object' &&
	!Array.isArray(userNitroConfig) &&
	userNitroConfig.routeRules &&
	typeof userNitroConfig.routeRules === 'object' &&
	!Array.isArray(userNitroConfig.routeRules)
		? userNitroConfig.routeRules
		: {}

export default defineNitroConfig({
	extends: ${JSON.stringify(importPath)},
	rootDir: '..',
	output: ${JSON.stringify({ dir: path.join(root, '.output') }, null, 2)},
	scanDirs: Array.from(new Set([...userScanDirs, ...aeroScanDirs])),
	routeRules: Object.fromEntries(
		Object.entries(aeroRouteRules).filter(([route]) => !(route in userRouteRules))
	),
	noPublicDir: true,
	replace: ${JSON.stringify(replace, null, 2)},
})
`

	const filePath = path.join(aeroDir, 'nitro.config.mjs')
	writeFileSync(filePath, content)

	return {
		aeroDir,
		filePath,
		content,
		conflictingRedirects,
		userConfigFile,
	}
}

function toRelativeModulePath(fromDir: string, targetFile: string): string {
	const relativePath = path.relative(fromDir, targetFile)
	return relativePath.startsWith('.') ? relativePath : `./${relativePath}`
}
